- name: Configure web.config for SQL connection string
  hosts: windows
  vars:
    ip_address: 54.219.58.73
    database_name: mydatabase
    db_username: sqluser
    db_password: Pa$$w0rd
  tasks:
    - name: Create web.config file
      template:
        src: templates/web.config.j2
        dest: c:/inetpub/wwwroot/web.config